//Bai 1a,b
console.log("hi I'm nahNi")
//Bai 1d
console.log("***")
console.log("***")
console.log("***")
console.log("***")
console.log("***")
//Bai 1e
console.log("")
console.log("     *")
console.log("    ***")
console.log("  *******")
console.log(" *********")
console.log("***********")
//Bai 1f
console.log("")
console.log(" ** **")
console.log("*  *  *")
console.log("*     *")
console.log(" *   *")
console.log("   *   ")
console.log('|`  |  /`   |   | |`  | |')
console.log('| ` | /- `  |-- | | ` | |')
console.log('|  `|/    ` |   | |  `| |')
